# Generated by Django 3.0.10 on 2020-11-02 13:21

from django.db import migrations, connection


def create_user_auth_groups(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute(
            'create table user_user_permissions('
                'id serial not null constraint user_user_permissions_pkey primary key,'
                'user_id integer not null,'
                'permission_id integer not null constraint user_user_permission_permission_id_9deb68a3_fk_auth_perm references auth_permission deferrable initially deferred,'
                'constraint user_user_permissions_user_id_permission_id_7dc6e2e0_uniq unique (user_id, permission_id)'
            ')'
        )

        cursor.execute('alter table user_user_permissions owner to postgres')

        cursor.execute('create index user_user_permissions_permission_id_9deb68a3 on user_user_permissions (permission_id)')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_user_auth_groups_table'),
    ]

    operations = [
        migrations.RunPython(create_user_auth_groups),
    ]
