# Generated by Django 3.0.10 on 2020-11-03 08:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_default_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
