# Generated by Django 3.0.10 on 2020-11-02 13:21

from django.db import migrations, connection


def set_user_auth_group(*args, **kwargs):
    with connection.cursor() as cursor:
        users = get_all_users(cursor)

        for user in users:
            cursor.execute('INSERT INTO user_auth_groups (user_id, group_id) VALUES (%s, %s)', [user, 2])

def get_all_users(cursor):
    cursor.execute('SELECT "id" FROM "user"')

    return cursor.fetchall()

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_add_default_groups'),
    ]

    operations = [
        migrations.RunPython(set_user_auth_group),
    ]
