# Generated by Django 3.0.10 on 2020-11-04 10:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201103_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
