# Generated by Django 3.0.10 on 2020-11-02 13:21

from django.db import migrations, connection


def add_is_superuser_field(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute(
            'alter table "user" '
                'ADD COLUMN is_superuser boolean not null default False'
        )

def add_is_staff_field(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute(
            'alter table "user" '
                'ADD COLUMN is_staff boolean not null default True'
        )

def add_deleted_field(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute(
            'alter table "user" '
                'ADD COLUMN deleted timestamp with time zone'
        )

def add_date_joined_field(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute(
            'alter table "user" '
                'ADD COLUMN date_joined timestamp with time zone not null default now()'
        )

def add_created_at_field(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute(
            'alter table "user" '
                'ADD COLUMN created_at timestamp with time zone not null default now()'
        )

def add_updated_at_field(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute(
            'alter table "user" '
                'ADD COLUMN updated_at timestamp with time zone not null default now()'
        )

def add_last_login_field(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute(
            'alter table "user" '
                'ADD COLUMN last_login timestamp with time zone'
        )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0005_set_user_auth_group'),
    ]

    operations = [
        migrations.RunPython(add_is_superuser_field),
        migrations.RunPython(add_is_staff_field),
        migrations.RunPython(add_date_joined_field),
        migrations.RunPython(add_last_login_field),
        migrations.RunPython(add_created_at_field),
        migrations.RunPython(add_updated_at_field),
        migrations.RunPython(add_deleted_field),
    ]
