# Generated by Django 3.0.10 on 2020-11-02 13:21

from django.db import migrations, connection


def add_deleted_field(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute(
            'alter table "allele" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "alleleassessment" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "alleleassessmentattachment" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "alleleassessmentreferenceassessment" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "alleleinterpretation" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "alleleinterpretationsnapshot" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "allelereport" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "analysis" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "analysisinterpretation" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "analysisinterpretationsnapshot" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "annotation" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "annotationjob" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "annotationshadowfrequency" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "annotationshadowtranscript" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "attachment" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "broadcast" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "clilog" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "customannotation" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "filterconfig" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "gene" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "geneassessment" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "genepanel" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "genepanel_phenotype" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "genotype" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "genotypesampledata" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "interpretationlog" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "interpretationstatehistory" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "jsonschema" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "phenotype" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "reference" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "referenceassessment" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "resourcelog" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "sample" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "transcript" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "usergroup" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "usergroupfilterconfig" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "usergroupgenepanel" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "useroldpassword" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )

        cursor.execute(
            'alter table "usersession" '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now(), '
                'ADD COLUMN deleted timestamp with time zone'
        )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('api', '0006_update_user_table'),
    ]

    operations = [
        migrations.RunPython(add_deleted_field),
    ]
