# Generated by Django 2.0.6 on 2018-09-11 02:50
import pydash
from django.db import connection, migrations

def get_user_group_id_or_create():
    with connection.cursor() as cursor:
        cursor.execute('SELECT "id" FROM "usergroup"')

        users_groups = cursor.fetchall()

        if len(users_groups) > 0:
            return users_groups[0]
        else:
            cursor.execute("INSERT INTO usergroup (id, name, config) VALUES (1, 'superuser-group', '{}')")

            return 1

def create_superadmin(*args, **kwargs):
    with connection.cursor() as cursor:
        user_group_id = get_user_group_id_or_create()

        cursor.execute(
            "INSERT INTO \"user\" (last_login,"
                    "is_superuser,"
                    "is_staff,"
                    "active,"
                    "date_joined,"
                    "email,"
                    "password,"
                    "password_expiry,"
                    "incorrect_logins,"
                    "first_name,"
                    "last_name,"
                    "username,"
                    "group_id,"
                    "config,"
                    "created_at,"
                    "updated_at)"
            "VALUES (NULL,"
                    "true,"
                    "false,"
                    "true,"
                    "'2018-09-11 08:56:27.268000',"
                    "'superadmin@ellaadmin.com',"
                    "'$2b$12$qMyZKaxhdgtGUQTP/TKIrObQPuKVvAjR8AKnwbfUgo19e8Xid3vMO',"
                    "'2030-12-31 00:00:27.268000',"
                    "0,"
                    "'Super',"
                    "'Admin',"
                    "'superuser',"
                    "%s,"
                    "\'{}\',"
                    "'2018-09-11 08:57:26.581000',"
                    "'2018-09-11 08:57:28.479000')" % user_group_id
            )

        cursor.execute("SELECT id FROM \"user\" WHERE email='superadmin@ellaadmin.com'")
        user_id = cursor.fetchone()[0]

        cursor.execute("SELECT id FROM auth_group WHERE name='admin'")
        group_id = cursor.fetchone()[0]

        cursor.execute("INSERT INTO user_auth_groups (user_id, group_id) VALUES (%s, %s)", [user_id, group_id])


def remove_superadmin(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute(
            "DELETE FROM user_auth_groups WHERE user_id=(SELECT id FROM api_users WHERE email='super-admin@ronasit.com')"
        )
        cursor.execute("DELETE FROM \"user\" WHERE email='superadmin@ellaadmin.com'")


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_update_user_group_table'),
    ]

    operations = [
        migrations.RunPython(create_superadmin, reverse_code=remove_superadmin),
    ]
