# Generated by Django 3.0.10 on 2020-11-02 13:21

from django.db import migrations, connection


def update_genepanel_table(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute(
            'alter table "genepanel" '
                'ADD COLUMN id serial, '
                'ADD COLUMN created_at timestamp with time zone not null default now(), '
                'ADD COLUMN updated_at timestamp with time zone not null default now()'
        )


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0012_create_django_admin_log_tables'),
    ]

    operations = [
        migrations.RunPython(update_genepanel_table),
    ]
