# Generated by Django 3.0.10 on 2021-02-04 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_inactive_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('MLPA', 'MLPA'), ('SEQ', 'SEQ'), ('NGS', 'NGS')], default='MLPA', max_length=255)),
                ('methodology', models.TextField(blank=True)),
                ('limitations', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'custom_test',
            },
        ),
        migrations.CreateModel(
            name='CustomTestGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('transcript', models.CharField(max_length=255)),
                ('custom_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CustomTest')),
            ],
            options={
                'db_table': 'custom_test_gene',
            },
        ),
        migrations.CreateModel(
            name='CustomTestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True)),
                ('custom_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CustomTest')),
            ],
            options={
                'db_table': 'custom_test_report',
            },
        ),
        migrations.CreateModel(
            name='CustomTestVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(max_length=255)),
                ('classification', models.CharField(blank=True, choices=[('BENIGN', 'Benign'), ('LIKELY_BENIGN', 'Likely Benign'), ('VARIANT_UNCERTAIN_SIGNIFICANCE', 'Variant of Uncertain Significance'), ('LIKELY_PATHOGENIC', 'Likely Pathogenic'), ('PATHOGENIC', 'Pathogenic'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=255)),
                ('zygosity', models.CharField(blank=True, choices=[('HOMOZYGOUS_REFERENCE', 'Homozygous Reference'), ('HETEROZYGOUS', 'Heterozygous'), ('HOMOZYGOUS_ALTERNATE', 'Homozygous Alternate')], default='HOMOZYGOUS_REFERENCE', max_length=255)),
                ('custom_test_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CustomTestGene')),
            ],
            options={
                'db_table': 'custom_test_variation',
            },
        ),
        migrations.CreateModel(
            name='CustomTestReportVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('custom_test_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CustomTestReport')),
                ('custom_test_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CustomTestVariation')),
            ],
            options={
                'db_table': 'custom_test_report_variation',
            },
        ),
        migrations.CreateModel(
            name='CustomTestReportResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('finding', models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('INCONCLUSIVE', 'Inconclusive')], default='POSITIVE', max_length=255)),
                ('custom_test_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.CustomTestReport')),
            ],
            options={
                'db_table': 'custom_test_report_result',
            },
        ),
        migrations.CreateModel(
            name='CustomTestReportInterpretation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpretation', models.TextField()),
                ('custom_test_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.CustomTestReport')),
            ],
            options={
                'db_table': 'custom_test_report_interpretation',
            },
        ),
        migrations.CreateModel(
            name='CustomTestReportGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('custom_test_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CustomTestGene')),
                ('custom_test_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CustomTestReport')),
            ],
            options={
                'db_table': 'custom_test_report_gene',
            },
        ),
    ]
