# Generated by Django 3.0.10 on 2021-01-12 10:42

import compositefk.fields
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '00016_add_inactive_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReportTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('MLPA', 'MLPA'), ('SEQ', 'SEQ'), ('NGS', 'NGS')], default='MLPA',
                                          max_length=255)),
                ('method', models.TextField(blank=True)),
                ('disclaimer', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'custom_report_test',
            },
        ),
        migrations.CreateModel(
            name='CustomReportGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('custom_report_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CustomReportTest')),
            ],
            options={
                'db_table': 'custom_report_gene',
            },
        ),
        migrations.CreateModel(
            name='CustomReportVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(max_length=255)),
                ('custom_report_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CustomReportGene')),
            ],
            options={
                'db_table': 'custom_report_variation',
            },
        ),
        migrations.CreateModel(
            name='CustomReportResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('custom_report_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CustomReportVariation')),
            ],
            options={
                'db_table': 'custom_report_result',
            },
        ),
        migrations.CreateModel(
            name='CustomReportInterpretation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpretations', models.TextField()),
                ('custom_report_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CustomReportResult')),
            ],
            options={
                'db_table': 'custom_report_interpretation',
            },
        ),
        migrations.CreateModel(
            name='CustomReportFullReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(null=True)),
                ('report_text', models.TextField(blank=True)),
                ('time_submitted', models.DateTimeField(blank=True)),
                ('custom_report_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CustomReportTest')),
            ],
            options={
                'db_table': 'custom_report_full_report',
            },
        ),
    ]
