# Generated by Django 3.0.10 on 2021-02-03 07:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_inactive_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReportGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('transcript', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'custom_report_gene',
            },
        ),
        migrations.CreateModel(
            name='CustomReportTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('MLPA', 'MLPA'), ('SEQ', 'SEQ'), ('NGS', 'NGS')], default='MLPA', max_length=255)),
                ('method', models.TextField(blank=True)),
                ('disclaimer', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'custom_report_test',
            },
        ),
        migrations.CreateModel(
            name='CustomReportVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('classification', models.CharField(choices=[('BENIGN', 'Benign'), ('LIKELY_BENIGN', 'Likely Benign'), ('VARIANT_UNCERTAIN_SIGNIFICANCE', 'Variant of Uncertain Significance'), ('LIKELY_PATHOGENIC', 'Likely Pathogenic'), ('PATHOGENIC', 'Pathogenic'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=255)),
                ('zygosity', models.CharField(choices=[('HOMOZYGOUS_REFERENCE', 'Homozygous Reference'), ('HETEROZYGOUS', 'Heterozygous'), ('HOMOZYGOUS_ALTERNATE', 'Homozygous Alternate')], default='HOMOZYGOUS_REFERENCE', max_length=255)),
                ('custom_report_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CustomReportGene')),
            ],
            options={
                'db_table': 'custom_report_variation',
            },
        ),
        migrations.CreateModel(
            name='CustomReportResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('finding', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('INCONCLUSIVE', 'Inconclusive')], default='POSITIVE', max_length=255)),
                ('custom_report_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.CustomReportTest')),
            ],
            options={
                'db_table': 'custom_report_result',
            },
        ),
        migrations.CreateModel(
            name='CustomReportInterpretation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpretations', models.TextField()),
                ('custom_report_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.CustomReportTest')),
            ],
            options={
                'db_table': 'custom_report_interpretation',
            },
        ),
        migrations.AddField(
            model_name='customreportgene',
            name='custom_report_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CustomReportTest'),
        ),
        migrations.CreateModel(
            name='CustomReportFullReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(null=True)),
                ('report_text', models.TextField(blank=True)),
                ('time_submitted', models.DateTimeField(blank=True)),
                ('custom_report_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.CustomReportTest')),
            ],
            options={
                'db_table': 'custom_report_full_report',
            },
        )
    ]
