# Generated by Django 3.0.10 on 2021-02-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210112_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='customreportgene',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customreportgene',
            name='transcript',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
