# Generated by Django 3.0.10 on 2021-02-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210204_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtestreportresult',
            name='custom_test_report',
        ),
        migrations.AddField(
            model_name='customtest',
            name='finding',
            field=models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('INCONCLUSIVE', 'Inconclusive')], default='POSITIVE', max_length=255),
        ),
        migrations.AddField(
            model_name='customtestreport',
            name='interpretation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customtestreport',
            name='result',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='CustomTestReportInterpretation',
        ),
        migrations.DeleteModel(
            name='CustomTestReportResult',
        ),
    ]
