# Generated by Django 3.0.10 on 2021-02-10 14:04

import compositefk.fields
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210205_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=255)),
                ('sample_type', models.CharField(blank=True, max_length=255)),
                ('sample_id', models.CharField(blank=True, max_length=255)),
                ('test_accession', models.CharField(blank=True, max_length=255)),
                ('test_ordered', models.CharField(blank=True, max_length=255)),
                ('test_code', models.CharField(blank=True, max_length=255)),
                ('ordered_by', models.CharField(blank=True, max_length=255)),
                ('sample_collection_date', models.DateTimeField(blank=True)),
                ('sample_accession_date', models.DateTimeField(blank=True)),
                ('report_date', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.AddField(
            model_name='customtest',
            name='patient',
            field=models.ForeignKey(to='api.Patient', on_delete=django.db.models.deletion.CASCADE, null=True)
        ),
    ]
