# Generated by Django 3.0.10 on 2021-02-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210202_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='customreportvariation',
            name='classification',
            field=models.CharField(choices=[('BENIGN', 'Benign'), ('LIKELY_BENIGN', 'Likely Benign'), ('VARIANT_UNCERTAIN_SIGNIFICANCE', 'Variant of Uncertain Significance'), ('LIKELY_PATHOGENIC', 'Likely Pathogenic'), ('PATHOGENIC', 'Pathogenic'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=255),
        ),
        migrations.AddField(
            model_name='customreportvariation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customreportvariation',
            name='zygosity',
            field=models.CharField(choices=[('HOMOZYGOUS_REFERENCE', 'Homozygous Reference'), ('HETEROZYGOUS', 'Heterozygous'), ('HOMOZYGOUS_ALTERNATE', 'Homozygous Alternate')], default='HOMOZYGOUS_REFERENCE', max_length=255),
        ),
    ]
