name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ "master", "development" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "master", "development" ]
    paths-ignore: [ "docs/**" ]


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # - name: Lint with flake8
      #   run: flake8

# With no caching at all the entire ci process takes 4m 30s to complete!
  # tests:
  #   runs-on: ubuntu-latest
  #   steps:

  #     - name: Checkout Code Repository
  #       uses: actions/checkout@v2

  #     - name: Run django and postgresql
  #       run:  docker-compose -f tests.yml up -d 

  #     - name: Run Django Tests
  #       run:  docker-compose -f tests.yml exec -T django python manage.py test

  #     - name: Tear down the Stack
  #       run:  docker-compose -f tests.yml down

  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    # needs: tests
    steps:
      - name: Checkout development
        uses: actions/checkout@v1
      - name: Add the private SSH key to the ssh-agent
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
      - name: rsync code from guthub to server
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          rsync -av ./ ec2-user@54.161.122.188:/home/ec2-user/efs/ella_admin_stg
          ENDSSH