name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ "master", "development" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "master", "development" ]
    paths-ignore: [ "docs/**" ]


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # - name: Lint with flake8
      #   run: flake8

# With no caching at all the entire ci process takes 4m 30s to complete!
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2
      - name: Run django and postgresql
        run:  docker-compose -f tests.yml up -d 
      - name: Run Django Tests
        run:  docker-compose -f tests.yml exec -T django python manage.py test
      - name: Tear down the Stack
        run:  docker-compose -f tests.yml down

  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/development'
    steps:
      - name: Checkout development
        uses: actions/checkout@v1
      - name: Add the private SSH key to the ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan 54.161.122.188 >> ~/.ssh/known_hosts
          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
      - name: rsync code from guthub to server
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          rsync -av ./ ec2-user@54.161.122.188:/home/ec2-user/efs/ella_admin_stg --exclude=ella-admin/settings/staging.py
      - name: restart docker-compose on server
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh ec2-user@54.161.122.188 "cd /home/ec2-user/efs/ella_admin_stg && docker-compose -f stg.yml up -d --force-recreate --build django && exit"
      - name: migrations
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh ec2-user@54.161.122.188 "cd /home/ec2-user/efs/ella_admin_stg && make migrate-django-stg && exit"
          
  push:
    name: Push to Dockerhub
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/development'
    steps:
      - name: Checkout development
        uses: actions/checkout@v1
      - name: Docker Build
        run:  docker-compose -f stg.yml build && export DIR="$(basename $(pwd))" && docker tag "${DIR}_django" dabbleofdevops/ella-admin
      - name: Push to Docker Hub
        env: # Set the secret in the env
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push dabbleofdevops/ella-admin
