name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ "master", "development" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "master", "development" ]
    paths-ignore: [ "docs/**" ]


jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: flake8

# With no caching at all the entire ci process takes 4m 30s to complete!
  pytest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Run django and postgresql
        run:  docker-compose -f tests.yml up -d 

      - name: Run Django Tests
        run:  docker-compose -f tests.yml exec -T django python manage.py test

      - name: Tear down the Stack
        run:  docker-compose -f tests.yml down

  # deploy:
  #   name: Deploy to staging
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout development
  #       uses: actions/checkout@v1
  #     - name: Add the private SSH key to the ssh-agent
  #       env:
  #         SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  #       run: |
  #         mkdir -p ~/.ssh
  #         ssh-agent -a $SSH_AUTH_SOCK > /dev/null
  #         ssh-keyscan github.com >> ~/.ssh/known_hosts
  #         ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
  #     - name: Build and deploy images on DigitalOcean
  #       env:
  #         SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  #       run: |
  #         scp  -o StrictHostKeyChecking=no -r ./.env ./docker-compose.prod.yml root@${{ secrets.DIGITAL_OCEAN_IP_ADDRESS }}:/app
  #         ssh -o StrictHostKeyChecking=no root@${{ secrets.DIGITAL_OCEAN_IP_ADDRESS }} << 'ENDSSH'
  #           cd /app
  #           source .env
  #           docker login docker.pkg.github.com -u testdrivenio -p ce70f1d4a3a906ce8ac24caa6870fd29f2273d30
  #           docker pull $WEB_IMAGE
  #           docker pull $NGINX_IMAGE
  #           docker-compose -f docker-compose.prod.yml up -d
  #         ENDSSH